### ISSUE TITLE
after Android O background services cannot be started?

### ISSUE THREAD

**Issue by jules15** [googlesamples/android-JobScheduler#10]
I'm not sure this example has been updated for Android O and beyond. How do you anticipate avoiding the following kind of exception?

Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.tildejps.collagio/.compose.FetchVersionInfoService (has extras) }: app is in background uid UidRecord{7155f20 u0a86 CAC  bg:+1m3s202ms idle change:idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1561)
       at android.app.ContextImpl.startService(ContextImpl.java:1516)
       at android.content.ContextWrapper.startService(ContextWrapper.java:657)
       at xxx.onStart(MainActivity.kt:541)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1382)
       at android.app.Activity.performStart(Activity.java:7151)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2949)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:194)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:157)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:72)
       at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
       at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4753)
       at android.app.ActivityThread.relaunchAllActivities(ActivityThread.java:4336)
       at android.app.ActivityThread.handleApplicationInfoChanged(ActivityThread.java:5195)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1789)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6649)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
